POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "a",
  "lastName": "def",
  "email": "abcde@gmail.com",
  "phone": "+94777648683",
  "age": 27,
  "status": "Active"
}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/a55e1a8c-a1da-41fc-90c3-37c747893b1c

###
PATCH http://localhost:8080/users/a55e1a8c-a1da-41fc-90c3-37c747893b1c
Content-Type: application/json

{
  "firstName": "pqrr",
  "lastName": "anh",
  "email": "qqqq@gmail.com",
  "phone": "0777648683",
  "age": 27,
  "status": "Active"
}

###

DELETE http://localhost:8080/users/a55e1a8c-a1da-41fc-90c3-37c747893b1c