POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "a",
  "lastName": "def",
  "email": "abc@gmail.com",
  "phone": "+94777648683",
  "age": 27,
  "status": "Active"
}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/059874e7-8e86-4292-9919-a7ec3705d5e9

###
PUT http://localhost:8080/users/059874e7-8e86-4292-9919-a7ec3705d5e9
Content-Type: application/json

{
  "firstName": "aqw",
  "lastName": "anh",
  "email": "qqqq@gmail.com",
  "phone": "0777648683",
  "age": 27,
  "status": "Active"
}

###

DELETE http://localhost:8080/users/059874e7-8e86-4292-9919-a7ec3705d5e9