// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID    uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       sql.NullInt32
	Status    string
	CreatedAt time.Time
}
